version: '3.8'

services:
  nestjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/evento
      - JWT_SECRET=fhghgvvt567(--èHGVGVV)fufuyguuygkyuubuyybudy-__-
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge