version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongodb:27017/learn_with_me
      - JWT_SECRET=fhghgvvt567(--èHGVGVV)fufuyguuygkyuubuyybudy-__-
      - NODE_ENV=production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=learn-with-me
    depends_on:
      - mongodb
      - minio
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000'
      - '9001:9001'  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    networks:
      - app-network

  # This service creates initial buckets and permissions
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting for minio...' && sleep 1; done;
      /usr/bin/mc mb myminio/learn-with-me;
      /usr/bin/mc policy set public myminio/learn-with-me;
      exit 0;
      "
    networks:
      - app-network

volumes:
  mongodb-data:
  minio-data:

networks:
  app-network:
    driver: bridge